apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: conditional-field-example
  title: Conditional Field Example
  description: A template demonstrating conditional fields
spec:
  type: service
  parameters:
    - title: Example Form
      required:
        - option
      properties:
        option:
          type: string
          title: Choose an Option
          enum:
            - Option A
            - Option B

        additionalField:
          type: string
          title: Additional Field (Visible only for Option A)

      ui: # UI Schema for conditional visibility
        additionalField:
          "ui:widget": hidden # Default state is hidden
        option:
          "ui:change": |
            if (formData.option === 'Option A') {
              uiSchema.additionalField["ui:widget"] = "text";
            } else {
              uiSchema.additionalField["ui:widget"] = "hidden";
            }
